study_record/qa/urls.py
from django.urls import path
from . import views


app_name = 'qa'
urlpatterns = [
    path('', views.QuestionAndAnswerView.as_view(), name='qa'),
    path('question-detail/<int:pk>', views.QuestionDetailView.as_view(), name='question_detail'),
    path('question-create', views.QuestionCreateView.as_view(), name='question_create'),
    path('add-supplement/<int:pk>', views.AddSupplementView.as_view(), name='add_supplement'),
    path('question-delete/<int:pk>', views.QuestionDeleteView.as_view(), name='question_delete'),
    path('answer-create/<int:pk>', views.AnswerCreateView.as_view(), name='answer_create'),
    path('answer-comment-create/<int:pk>/<int:a_pk>', views.CommentCreateView.as_view(), name='answer_comment_create'),
    path('self-resolution/<int:pk>', views.SelfResolutionView.as_view(), name='self_resolution'),
    path('set-best-answer/<int:pk>/<int:a_pk>', views.SetBestAnswerView.as_view(), name='set_best_answer'),
]

study_record/study/urls.py
from django.urls import path
from . import views


app_name = 'study'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('studyrecord-create', views.StudyRecordCreateView.as_view(), name='studyrecord_create'),
    path('studyrecord-update/<int:pk>', views.StudyRecordUpdateView.as_view(), name='studyrecord_update'),
    path('studyrecord-delete/<int:pk>', views.StudyRecordDeleteView.as_view(), name='studyrecord_delete'),
    path('report', views.ReportView.as_view(), name='report'),
    path('get-bar-chart-data-week', views.GetBarChartDataWeek.as_view(), name='get_bar_chart_data_week'),
    path('get-bar-chart-data-month', views.GetBarChartDataMonth.as_view(), name='get_bar_chart_data_month'),
    path('get-bar-chart-data-year', views.GetBarChartDataYear.as_view(), name='get_bar_chart_data_year'),
    path('subject', views.SubjectView.as_view(), name='subject'),
    path('subject-create', views.SubjectCreateView.as_view(), name='subject_create'),
    path('subject/subject-update/<int:pk>', views.SubjectUpdateView.as_view(), name='subject_update'),
    path('subject/subject-delete/<int:pk>', views.SubjectDeleteView.as_view(), name='subject_delete'),
    path('account-search', views.AccountSearchView.as_view(), name='account_search'),
    path('<int:pk>', views.AccountDetailView.as_view(), name='account_detail'),
    path('<int:pk>/following', views.AccountFollowingView.as_view(), name='account_following'),
    path('<int:pk>/followers', views.AccountFollowersView.as_view(), name='account_followers'),
    path('<int:pk>/follow', views.FollowView.as_view(), name='follow'),
    path('<int:pk>/unfollow', views.UnfollowView.as_view(), name='unfollow'),
    path('<int:pk>/edit', views.AccountUpdateView.as_view(), name='account_update'),
]

study_record/study_record/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from . import settings_dev


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('study.urls')),
    path('qa', include('qa.urls')),
    path('accounts/', include('allauth.urls')),
]

# 開発サーバーでメディアを配信できるようにする設定
urlpatterns += static(settings_dev.STATIC_URL, document_root=settings_dev.STATICFILES_DIRS)
urlpatterns += static(settings_dev.MEDIA_URL, document_root=settings_dev.MEDIA_ROOT)

study_record/qa/models.py
from django.db import models
from accounts.models import CustomUser

# Create your models here.
class Question(models.Model):
    user        = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    image       = models.ImageField(upload_to='question_images/', null=True, blank=True, default='')
    title       = models.CharField(max_length=200)
    text        = models.TextField()
    supplement  = models.TextField(null=True, blank=False)
    is_resolved = models.BooleanField(default=False)
    created_at  = models.DateTimeField(auto_now_add=True)
    updated_at  = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.text


class Answer(models.Model):
    user            = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    question        = models.ForeignKey(Question, on_delete=models.PROTECT)
    text            = models.TextField()
    image           = models.ImageField(upload_to='answer_images/', null=True, blank=True, default='')
    is_best         = models.BooleanField(default=False)
    self_resolution = models.BooleanField(default=False)
    created_at      = models.DateTimeField(auto_now_add=True)
    updated_at      = models.DateTimeField(auto_now=True)


class Comment(models.Model):
    user       = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    answer     = models.ForeignKey(Answer, on_delete=models.PROTECT, related_name='comments')
    text       = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

study_record/qa/forms.py
from django import forms
from .models import Question, Answer


class QuestionCreateForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('title', 'text', 'image')


class AnswerCreateForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ('text', 'image')

study_record/qa/views.py
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.views import generic
from django.db.models import Prefetch, Q
from .models import Question, Answer, Comment
from .forms import QuestionCreateForm, AnswerCreateForm
import datetime as dt

# Create your views here.
class QuestionAndAnswerView(LoginRequiredMixin, generic.ListView):
    template_name = 'qa.html'
    paginate_by = 30

    def get_queryset(self):
        query = self.request.GET.get('query')
        tab = self.request.GET.get('tab')
        sort = self.request.GET.get('sort')

        queryset = Question.objects.order_by('-created_at')
        if query:
            queryset = queryset.filter(Q(text__icontains=query) | Q(title__icontains=query))

        if tab == 'resolved':
            queryset = queryset.filter(is_resolved=True)
        elif tab == 'unresolved':
            queryset = queryset.filter(is_resolved=False)

        if sort == 'old':
            queryset = queryset.order_by('created_at')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = self.request.GET.get('query')
        context['tab'] = self.request.GET.get('tab') or 'all'
        context['sort'] = self.request.GET.get('sort') or 'new'
        return context


class QuestionDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = 'question_detail.html'
    model = Question

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        answer_list = Answer.objects.select_related('user').prefetch_related(
            Prefetch(
                'comments',
                queryset=Comment.objects.select_related('user').order_by('created_at')
            )
        ).filter(question=self.kwargs['pk']).order_by('-created_at').order_by('-self_resolution').order_by('-is_best')

        is_user_answered = answer_list.filter(user=self.request.user).exists()
        context['answer_list'] = answer_list
        context['answer_count'] = answer_list.count()
        context['is_user_answered'] = is_user_answered
        return context


class CommentCreateView(LoginRequiredMixin, generic.View):
    def post(self, request, *args, **kwargs):
        comment = Comment.objects.create(
            user=request.user,
            text=request.POST['text'],
            answer=Answer.objects.get(pk=kwargs['a_pk'])
        )
        comment.save()
        messages.success(request, '回答にコメントしました。')
        return HttpResponseRedirect(reverse_lazy('qa:question_detail', kwargs={'pk': kwargs['pk']}))


class QuestionCreateView(LoginRequiredMixin, generic.CreateView):
    template_name = 'question_create.html'
    form_class = QuestionCreateForm
    success_url = reverse_lazy('qa:qa')

    def form_valid(self, form):
        question = form.save(commit=False)
        # ログインユーザーのIDを保存
        question.user = self.request.user
        # 締め切りを一週間後に設定
        deadline = dt.datetime.now().astimezone().replace(hour=0, minute=0, second=0, microsecond=0) + dt.timedelta(days=8)
        question.deadline = deadline
        question.save()

        messages.success(self.request, '質問を投稿しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, '質問の投稿に失敗しました。')
        return super().form_invalid(form)


class AddSupplementView(LoginRequiredMixin, generic.UpdateView):
    template_name = 'add_supplement.html'
    model = Question
    fields = ('supplement', )

    def get_success_url(self):
        return reverse_lazy('qa:question_detail', kwargs={'pk': self.kwargs['pk']})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['question'] = Question.objects.get(pk=self.kwargs['pk'])
        return context

    def form_valid(self, form):
        messages.success(self.request, '補足説明を追加しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, '補足説明の追加に失敗しました。')
        return super().form_invalid(form)


class QuestionDeleteView(LoginRequiredMixin, generic.View):
    def post(self, request, *args, **kwargs):
        question = Question.objects.get(pk=kwargs['pk'])
        question.delete()
        messages.success(request, '質問を削除しました。')
        return HttpResponseRedirect(reverse_lazy('qa:qa'))


class AnswerCreateView(LoginRequiredMixin, generic.CreateView):
    template_name = 'answer_create.html'
    form_class = AnswerCreateForm

    def get_success_url(self):
        return reverse_lazy('qa:question_detail', kwargs={'pk': self.kwargs['pk']})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['question'] = Question.objects.get(pk=self.kwargs['pk'])
        return context

    def form_valid(self, form):
        answer = form.save(commit=False)
        question = Question.objects.get(pk=self.kwargs['pk'])

        answer.user = self.request.user
        answer.question = Question.objects.get(pk=self.kwargs['pk'])
        answer.save()

        messages.success(self.request, '回答を投稿しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, '回答の作成に失敗しました。')
        return super().form_invalid(form)


class SelfResolutionView(LoginRequiredMixin, generic.CreateView):
    template_name = 'self_resolution.html'
    form_class = AnswerCreateForm

    def get_success_url(self):
        return reverse_lazy('qa:question_detail', kwargs={'pk': self.kwargs['pk']})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['question'] = Question.objects.get(pk=self.kwargs['pk'])
        return context

    def form_valid(self, form):
        answer = form.save(commit=False)
        question = Question.objects.get(pk=self.kwargs['pk'])

        answer.user = self.request.user
        answer.question = question
        answer.self_resolution = True
        answer.save()

        question.is_resolved = True
        question.save()

        messages.success(self.request, '回答を自己解決に設定しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, '自己解決の設定に失敗しました。')
        return super().form_invalid(form)


class SetBestAnswerView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'set_best_answer.html'

    def post(self, request, *args, **kwargs):
        answer = Answer.objects.get(pk=kwargs['a_pk'])
        answer.is_best = True
        answer.save()

        question = Question.objects.get(pk=kwargs['pk'])
        question.is_resolved = True
        question.save()

        messages.success(request, 'ベストアンサーを設定しました。')
        return HttpResponseRedirect(reverse_lazy('qa:question_detail', kwargs={'pk': kwargs['pk']}))

study_record/qa/templates/add_supplement.html
{% extends 'base.html' %}

{% load static %}

{% load widget_tweaks %}

{% block title %}補足説明の追加 | StudyRecord{% endblock %}

{% block contents %}
<main class="container-md" style="max-width: 720px; margin-bottom: 10rem;">
    <h4 class="mb-3">補足説明の追加</h4>
    <div class="card card-body mb-4 p-4">
        <h5 class="card-title">{{ question.title }}</h5>
        <hr class="mt-1">
        <p class="card-text">{{ question.text|linebreaksbr }}</p>
        {% if question.image %}
            <div class="mb-3">
                <a role="button" data-bs-toggle="modal" data-bs-target="#imageModal" data-image="{{ question.image }}">
                    <img src="/media/{{ question.image }}" class="rounded mx-auto d-block" style="object-fit: cover;" width="320" height="240"/>
                </a>
            </div>
        {% endif %}
    </div>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-4">
            <label class="form-label" for="{{ form.supplement.id_for_label }}">説明文</label>
            {% render_field form.supplement class='form-control' %}
        </div>
        <button type="submit" class="btn btn-primary">送信</button>
    </form>

    <!-- 画像表示モーダル -->
    <div class="modal fade" id="imageModal" tabindex="-1" aria-labelledby="imageModalLabel">
        <div class="modal-dialog modal-lg modal-dialog-centered">
            <div class="modal-content">
                <img class="col-12" id="image" src="/media/{{ question.image }}"/>
            </div>
        </div>
    </div>
</main>
{% endblock %}

{% block script %}
<script>
    document.getElementById('imageModal').addEventListener('show.bs.modal', event => {
        targetEl = event.relatedTarget;
        const image = targetEl.dataset.image;
        document.getElementById('image').setAttribute('src', '/media/' + image);
    });
</script>
{% endblock %}

study_record/qa/templates/qa.html
{% extends 'base.html' %}

{% load static %}

{% load widget_tweaks %}

{% block title %}Q&ampA | StudyRecord{% endblock %}

{% block active_qa %}active{% endblock %}

{% block contents %}
<main class="container-md" style="margin-bottom: 10rem;">
    <div class="row">
        <div class="col-md-8">
            <form method="get">
                <div class="input-group mb-3">
                    <input type="search" class="form-control" name="query" placeholder="質問を検索">
                    <button type="submit" class="btn btn-primary"><i class="material-symbols-outlined align-middle">search</i></button>
                </div>
            </form>
            <ul class="nav nav-tabs">
                <li class="nav-item">
                    <a class="nav-link {% if tab == 'all' %}active{% endif %}" {% if tab == 'all' %}aria-current="page"{% endif %} href="?tab=all{% if query %}&query={{ query }}{% endif %}">すべて</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if tab == 'unresolved' %}active{% endif %}" {% if tab == 'unresolved' %}aria-current="page"{% endif %} href="?tab=unresolved{% if query %}&query={{ query }}{% endif %}">未解決</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if tab == 'resolved' %}active{% endif %}" {% if tab == 'resolved' %}aria-current="page"{% endif %} href="?tab=resolved{% if query %}&query={{ query }}{% endif %}">解決済み</a>
                </li>
            </ul>
            <ul class="list-group list-group-flush list-group-border-bottom">
                <li class="list-group-item">
                    <div class="row g-1 align-items-center">
                        <div class="col-auto">
                            <label for="sort-select" class="col-form-label">表示順</label>
                        </div>
                        <div class="col-auto me-2">
                            <select id="sort-select" class="form-select form-select-sm">
                                <option value="new" {% if sort == 'new' %}selected{% endif %}>投稿日時の新しい順</option>
                                <option value="old" {% if sort == 'old' %}selected{% endif %}>投稿日時の古い順</option>
                            </select>
                        </div>
                    </div>
                </li>
                {% if question_list %}
                    {% for question in question_list %}
                        <li class="list-group-item position-relative">
                            <div class="d-flex align-item-center">
                                <div class="d-flex flex-column justify-content-evenly py-2">
                                    <a class="stretched-link text-decoration-none text-break" href="{% url 'qa:question_detail' question.id %}">{{ question.title|truncatechars:100 }}</a>
                                    <div class="hstack gap-3 mt-1">
                                        <small class="text-muted">{{ question.created_at|date:'n/j G:i' }}</small>
                                        {% if question.is_resolved %}
                                            <small class="text-muted">解決済み</small>
                                        {% else %}
                                            <small class="text-muted">未解決</small>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </li>
                    {% endfor %}
                {% else %}
                    <li class="list-group-item text-center py-5">質問がありません。</li>
                {% endif %}
            </ul>

            <!-- ページネーション -->
            {% if is_paginated %}
                <ul class="pagination justify-content-center" style="margin-top: 3rem;">
                    <!-- 前ページへのリンク -->
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if query %}&query={{ query }}{% endif %}{% if tab %}&tab={{ tab }}{% endif %}{% if sort %}&sort={{ sort }}{% endif %}">&laquo;</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled"><a class="page-link">&laquo;</a></li>
                    {% endif %}
                    <!-- ページ数表示 -->
                    {% for page_num in page_obj.paginator.page_range %}
                        {% if page_obj.number == page_num %}
                            <li class="page-item active"><a class="page-link" href="#">{{ page_num }}</a></li>
                        {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{ page_num }}{% if query %}&query={{ query }}{% endif %}{% if tab %}&tab={{ tab }}{% endif %}{% if sort %}&sort={{ sort }}{% endif %}">{{ page_num }}</a></li>
                        {% endif %}
                    {% endfor %}
                    <!-- 次ページへのリンク -->
                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}{% if query %}&query={{ query }}{% endif %}{% if tab %}&tab={{ tab }}{% endif %}{% if sort %}&sort={{ sort }}{% endif %}">&raquo;</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled"><a class="page-link">&raquo;</a></li>
                    {% endif %}
                </ul>
            {% endif %}
        </div>
        <div class="col-md-4 d-none d-md-block mb-3">
            <div style="position: sticky; top: 5rem;">
                <a class="btn btn-primary col-12 mb-3" href="{% url 'qa:question_create' %}" role="button">質問する</a>
            </div>
        </div>
    </div>
    <a class="btn btn-primary rounded-circle d-md-none position-fixed bottom-0 end-0 m-3 d-flex justify-content-center align-items-center" style=" width: 56px; height: 56px;" href="{% url 'qa:question_create' %}" role="button"><div class="material-symbols-outlined">add</div></a>
</main>
{% endblock %}

{% block script %}
<script>
    function getOptionElement(select, value) {
        for (let i = 0; i < select.options.length; i++) {
            if (select.options[i].value === value) return select.options[i];
        }
        return null;
    }

    const sortSelect = document.getElementById('sort-select');

    sortSelect.onchange = () => {
        const url = new URL(window.location);
        url.searchParams.delete('sort');
        url.searchParams.delete('page');
        url.searchParams.append('sort', sortSelect.value);
        window.location.href = url.href;
    }
</script>
{% endblock %}

study_record/qa/templates/question_detail.html
{% extends 'base.html' %}

{% load static %}

{% load widget_tweaks %}

{% block title %}質問詳細 | StudyRecord{% endblock %}

{% block contents %}
<main class="container-md" style="max-width: 960px; margin-bottom: 10rem;">
    <!-- 質問 -->
    <div class="card mb-5">
        <div class="card-body mx-md-5 my-3">

            <div class="hstack gap-3 mb-3">
                <a class="text-decoration-none" href="{% url 'study:account_detail' question.user.pk %}">
                    {% if question.user.icon %}
                        <img src="/media/{{ question.user.icon }}" alt="{{ question.user.username }}" width="28" height="28" class="rounded-circle">
                    {% else %}
                        <img src="{% static 'images/default_icon.png' %}" alt="{{ user.username }}" width="28" height="28" class="rounded-circle">
                    {% endif %}
                    <span>{{ question.user.username }}</span>
                </a>
                <small class="text-muted">{{ question.created_at|date:'Y/n/j G:i' }}</small>
                {% if question.user.pk == user.pk %}
                    {% if not question.supplement or answer_count == 0 %}
                        <div class="dropdown ms-auto">
                            <a href="#" data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="bi bi-three-dots"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-menu-end">
                                {% if not question.supplement %}
                                    <li>
                                        <a class="dropdown-item" href="{% url 'qa:add_supplement' question.pk %}" role="button">補足説明の追加</a>
                                    </li>
                                {% endif %}
                                <!-- 回答数が0の場合のみ削除できる -->
                                {% if answer_count == 0 %}
                                    <li>
                                        <button class="dropdown-item" type="button" class="dropdown-item" data-bs-toggle="modal" data-bs-target="#deletionModal">削除</button>
                                    </li>
                                {% endif %}
                            </ul>
                        </div>
                    {% endif %}
                {% endif %}
            </div>

            <h4>{{ question.title }}</h4>

            <p class="card-text mb-3">{{ question.text|linebreaksbr }}</p>

            {% if question.image %}
                <div class="mb-3">
                    <a role="button" data-bs-toggle="modal" data-bs-target="#imageModal" data-image="{{ question.image }}">
                        <img src="/media/{{ question.image }}" class="rounded mx-auto d-block" style="object-fit: cover;" width="320" height="240"/>
                    </a>
                </div>
            {% endif %}

            {% if question.supplement %}
                <div class="card card-body bg-light mb-3">
                    <strong>補足</strong>
                    <span>{{ question.supplement }}</span>
                </div>
            {% endif %}

            <div class="hstack">
                <!-- ユーザーが未回答の場合 -->
                {% if not is_user_answered %}
                    {% if question.user.pk != user.pk %}
                        <a class="btn btn-primary" href="{% url 'qa:answer_create' question.pk %}" role="button">回答する</a>
                    {% elif not question.is_resolved %}
                        <a class="btn btn-primary" href="{% url 'qa:self_resolution' question.pk %}" role="button">自己解決</a>
                    {% endif %}
                {% endif %}
            </div>

        </div>
    </div>

    <!-- 回答 -->
    <h4>{{ answer_count }}件の回答</h4>
    <ul class="list-group list-group-flush list-group-border-top-bottom">
        {% if answer_list %}
            {% for answer in answer_list %}
                <li class="list-group-item px-md-5 py-4">
                    <div class="hstack gap-3 mb-3">
                        <a class="text-decoration-none" href="{% url 'study:account_detail' answer.user.pk %}">
                            {% if answer.user.icon %}
                                <img src="/media/{{ answer.user.icon }}" alt="{{ answer.user.username }}" width="28" height="28" class="rounded-circle">
                            {% else %}
                                <img src="{% static 'images/default_icon.png' %}" alt="{{ answer.user.username }}" width="28" height="28" class="rounded-circle">
                            {% endif %}
                            <span>{{ answer.user.username }}</span>
                        </a>
                        <small class="text-muted">{{ answer.created_at|date:'Y/n/j G:i' }}</small>
                    </div>
                    {% if answer.is_best %}
                        <div class="badge text-bg-success fs-6 mb-3">ベストアンサー</div>
                    {% elif answer.self_resolution %}
                        <div class="badge text-bg-success fs-6 mb-3">自己解決</div>
                    {% elif question.user.pk == user.pk and not question.is_resolved %}
                        <a class="d-block mb-3" href="{% url 'qa:set_best_answer' question.pk answer.pk %}">ベストアンサーにする</a>
                    {% endif %}

                    <p class="text-break mb-4">{{ answer.text|linebreaksbr }}</p>
                    {% if answer.image %}
                        <div class="col-md-7 mx-auto mb-3">
                            <a role="button" data-bs-toggle="modal" data-bs-target="#imageModal" data-image="{{ answer.image }}">
                                <img class="col-12" src="/media/{{ answer.image }}"/>
                            </a>
                        </div>
                    {% endif %}

                    {% for comment in answer.comments.all %}
                        <div class="answer-comment mb-3 px-3">
                            <div class="hstack gap-3 mb-3">
                                <a class="text-decoration-none" href="{% url 'study:account_detail' comment.user.pk %}">
                                    {% if comment.user.icon %}
                                        <img src="/media/{{ comment.user.icon }}" alt="{{ comment.user.pk }}" width="28" height="28" class="rounded-circle">
                                    {% else %}
                                        <img src="{% static 'images/default_icon.png' %}" alt="{{ comment.user.pk }}" width="28" height="28" class="rounded-circle">
                                    {% endif %}
                                    <span>{{ comment.user.username }}</span>
                                </a>
                                <small class="text-muted">{{ comment.created_at|date:'Y/n/j G:i' }}</small>
                            </div>
                            <p class="text-break">{{ comment.text|linebreaksbr }}</p>
                        </div>
                    {% endfor %}
                    <button type="button" class="btn btn-primary btn-sm" data-bs-toggle="collapse" data-bs-target="#collapseComment{{ answer.pk }}" aria-expanded="false" aria-controls="collapseComment">
                        コメントする
                    </button>
                    <div class="collapse mt-3" id="collapseComment{{ answer.pk }}">
                        <div class="card card-body">
                            <form method="post" action="{% url 'qa:answer_comment_create' question.pk answer.pk %}">
                                {% csrf_token %}
                                <textarea name="text" class="form-control mb-3" rows="2" placeholder="コメントを入力" required></textarea>
                                <button type="submit" class="btn btn-primary btn-sm">送信</button>
                            </form>
                        </div>
                    </div>
                </li>
            {% endfor %}
        {% else %}
            <li class="list-group-item text-center py-5">回答がありません</li>
        {% endif %}
    </ul>

    <!-- 画像表示モーダル -->
    <div class="modal fade" id="imageModal" tabindex="-1" aria-labelledby="imageModalLabel">
        <div class="modal-dialog modal-lg modal-dialog-centered">
            <div class="modal-content">
                <img class="col-12" id="image" src="/media/{{ question.image }}"/>
            </div>
        </div>
    </div>

    <!-- 記録削除モーダル -->
    <div class="modal fade" id="deletionModal" tabindex="-1" aria-labelledby="deletionModalLabel">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="deletionModalLabel">質問の削除</h1>
                </div>
                <div class="modal-body">
                    <p>この質問を削除しますか？</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">キャンセル</button>
                    <form method="post" action="{% url 'qa:question_delete' question.pk %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">削除する</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

{% block script %}
<script>
    document.getElementById('imageModal').addEventListener('show.bs.modal', event => {
        targetEl = event.relatedTarget;
        const image = targetEl.dataset.image;
        document.getElementById('image').setAttribute('src', '/media/' + image);
    });
</script>
{% endblock %}

study_record/qa/templates/set_best_answer.html
{% extends 'base.html' %}

{% load static %}

{% load widget_tweaks %}

{% block title %}ベストアンサーの設定 | StudyRecord{% endblock %}

{% block contents %}
<main class="container-md" style="max-width: 720px; margin-bottom: 10rem;">
    <h4 class="mb-3">ベストアンサーの設定</h4>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">ベストアンサーに設定する</button>
    </form>
</main>
{% endblock %}