study_record/qa/urls.py
from django.urls import path
from . import views


app_name = 'qa'
urlpatterns = [
    path('', views.QuestionAndAnswerView.as_view(), name='qa'),
    path('question-detail/<int:pk>', views.QuestionDetailView.as_view(), name='question_detail'),
    path('question-create', views.QuestionCreateView.as_view(), name='question_create'),
    path('add-supplement/<int:pk>', views.AddSupplementView.as_view(), name='add_supplement'),
    path('question-delete/<int:pk>', views.QuestionDeleteView.as_view(), name='question_delete'),
    path('answer-create/<int:pk>', views.AnswerCreateView.as_view(), name='answer_create'),
    path('answer-comment-create/<int:pk>/<int:a_pk>', views.CommentCreateView.as_view(), name='answer_comment_create'),
    path('self-resolution/<int:pk>', views.SelfResolutionView.as_view(), name='self_resolution'),
    path('set-best-answer/<int:pk>/<int:a_pk>', views.SetBestAnswerView.as_view(), name='set_best_answer'),
]

study_record/study/urls.py
from django.urls import path
from . import views


app_name = 'study'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('studyrecord-create', views.StudyRecordCreateView.as_view(), name='studyrecord_create'),
    path('studyrecord-update/<int:pk>', views.StudyRecordUpdateView.as_view(), name='studyrecord_update'),
    path('studyrecord-delete/<int:pk>', views.StudyRecordDeleteView.as_view(), name='studyrecord_delete'),
    path('report', views.ReportView.as_view(), name='report'),
    path('get-bar-chart-data-week', views.GetBarChartDataWeek.as_view(), name='get_bar_chart_data_week'),
    path('get-bar-chart-data-month', views.GetBarChartDataMonth.as_view(), name='get_bar_chart_data_month'),
    path('get-bar-chart-data-year', views.GetBarChartDataYear.as_view(), name='get_bar_chart_data_year'),
    path('subject', views.SubjectView.as_view(), name='subject'),
    path('subject-create', views.SubjectCreateView.as_view(), name='subject_create'),
    path('subject/subject-update/<int:pk>', views.SubjectUpdateView.as_view(), name='subject_update'),
    path('subject/subject-delete/<int:pk>', views.SubjectDeleteView.as_view(), name='subject_delete'),
    path('account-search', views.AccountSearchView.as_view(), name='account_search'),
    path('<int:pk>', views.AccountDetailView.as_view(), name='account_detail'),
    path('<int:pk>/following', views.AccountFollowingView.as_view(), name='account_following'),
    path('<int:pk>/followers', views.AccountFollowersView.as_view(), name='account_followers'),
    path('<int:pk>/follow', views.FollowView.as_view(), name='follow'),
    path('<int:pk>/unfollow', views.UnfollowView.as_view(), name='unfollow'),
    path('<int:pk>/edit', views.AccountUpdateView.as_view(), name='account_update'),
]

study_record/study_record/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from . import settings_dev


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('study.urls')),
    path('qa', include('qa.urls')),
    path('accounts/', include('allauth.urls')),
]

# 開発サーバーでメディアを配信できるようにする設定
urlpatterns += static(settings_dev.STATIC_URL, document_root=settings_dev.STATICFILES_DIRS)
urlpatterns += static(settings_dev.MEDIA_URL, document_root=settings_dev.MEDIA_ROOT)

study_record/study/models.py
from django.db import models
from accounts.models import CustomUser
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.
class Subject(models.Model):
    user         = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    name         = models.CharField(max_length=50)
    color        = models.CharField(max_length=7, default='#ffa8a8')
    is_available = models.BooleanField(default=True)
    created_at   = models.DateTimeField(auto_now_add=True)
    updated_at   = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class PublicationChoices(models.TextChoices):
    FOLLOW  = 'follow', 'フォロワーに公開'
    PRIVATE = 'private', '非公開'


class StudyRecord(models.Model):
    user        = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    subject     = models.ForeignKey(Subject, on_delete=models.CASCADE)
    studied_at  = models.DateTimeField()
    minutes     = models.IntegerField(default=30, validators=[MinValueValidator(5), MaxValueValidator(1440)])
    publication = models.CharField(max_length=10, choices=PublicationChoices.choices, default='follow')
    created_at  = models.DateTimeField(auto_now_add=True)
    updated_at  = models.DateTimeField(auto_now=True)

study_record/study/forms.py
from django import forms
from django.db import models
from .models import StudyRecord, Subject


class StudyRecordForm(forms.ModelForm):
    subject = forms.ModelChoiceField(label='教科', queryset=Subject.objects.none())

    # ログインユーザーの教科のうち、使用可能なもの（is_available == True）を選択肢にする
    def __init__(self, user=None, *args, **kwargs):
        self.base_fields['subject'].queryset = Subject.objects.filter(user=user, is_available=True)
        super().__init__(*args, **kwargs)

    class Meta:
        model = StudyRecord
        fields = ('subject', 'studied_at', 'minutes', 'publication')


class SubjectCreateForm(forms.ModelForm):
    class Meta:
        model = Subject
        fields = ('name', 'color')

study_record/study/views.py
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.db.models import Q
from .models import StudyRecord, Subject
from accounts.models import CustomUser, Connection
from .forms import StudyRecordForm, SubjectCreateForm
import datetime as dt
from .helpers import *

# Create your views here.
class HomeView(LoginRequiredMixin, generic.ListView):
    template_name = 'home.html'
    paginate_by = 10

    def get_queryset(self):
        queryset = StudyRecord.objects.select_related().filter(user=self.request.user).order_by('-studied_at')
        for row in queryset:
            row.minutes = to_time_str(row.minutes)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        following = Connection.objects.filter(follower=self.request.user).values_list('following', flat=True)
        following_records = StudyRecord.objects.select_related().filter(user__in=following, publication='follow').order_by('-studied_at')
        for row in following_records:
            row.minutes = to_time_str(row.minutes)
        context['following_records'] = following_records

        return context


class StudyRecordCreateView(LoginRequiredMixin, generic.CreateView):
    template_name = 'studyrecord_create.html'
    form_class = StudyRecordForm
    success_url = reverse_lazy('study:home')

    # 教科の選択肢を取得するためにStudyRecordFormにログインユーザーIDを渡す
    def get_form_kwargs(self):
        kwargs = super(StudyRecordCreateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    # StudyRecordモデルのuserフィールドにログインユーザーのIDを保存する
    def form_valid(self, form):
        studyrecord = form.save(commit=False)
        studyrecord.user = self.request.user
        studyrecord.save()

        messages.success(self.request, '記録を作成しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, '記録の作成に失敗しました。')
        return super().form_invalid(form)


class StudyRecordUpdateView(LoginRequiredMixin, generic.UpdateView):
    template_name = 'studyrecord_update.html'
    model = StudyRecord
    form_class = StudyRecordForm
    success_url = reverse_lazy('study:home')

    # 教科の選択肢を取得するためにStudyRecordFormにログインユーザーIDを渡す
    def get_form_kwargs(self):
        kwargs = super(StudyRecordUpdateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['study_record_pk'] = self.kwargs['pk']
        return context

    def form_valid(self, form):
        messages.success(self.request, '記録を更新しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "記録の更新に失敗しました。")
        return super().form_invalid(form)


class StudyRecordDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = StudyRecord
    success_url = reverse_lazy('study:home')

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, '記録を削除しました。')
        return super().delete(request, *args, **kwargs)


class ReportView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'report.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        studyrecord = StudyRecord.objects.filter(user=self.request.user).order_by('studied_at').select_related()

        now = dt.datetime.now().astimezone()

        t_start, t_end = day_start_end(now)
        w_start, w_end = week_start_end(now)
        m_start, m_end = month_start_end(now)

        context['pie_chart'] = pie_chart_data(studyrecord)

        context['today_sum'] = to_time_str(minutes_sum(studyrecord, t_start, t_end))
        context['week_sum'] = to_time_str(minutes_sum(studyrecord, w_start, w_end))
        context['month_sum'] = to_time_str(minutes_sum(studyrecord, m_start, m_end))
        context['total'] = to_time_str(minutes_sum(studyrecord))

        return context


class GetBarChartDataWeek(LoginRequiredMixin, generic.View):
    def get(self, request, *args, **kwargs):
        now = dt.datetime.now().astimezone()
        w_start, w_end = week_start_end(now)

        # 1週間分のデータを取得する
        queryset = StudyRecord.objects.filter(user=request.user, studied_at__range=(w_start, w_end)).order_by('studied_at').select_related()

        # 横軸ラベルを作る
        labels = []
        for i in range(7):
            date = w_start + dt.timedelta(days=i)
            weekday = ('日', '月', '火', '水', '木', '金', '土')[i]
            date_str = f'{date.month}/{date.day} ({weekday})'
            labels.append(date_str)

        data = {
            'labels': labels,
            'datasets': barchart_datasets(queryset, w_start, w_end)
        }

        return JsonResponse(data)


class GetBarChartDataMonth(LoginRequiredMixin, generic.View):
    def get(self, request, *args, **kwargs):
        now = dt.datetime.now().astimezone()
        m_start, m_end = month_start_end(now)

        # 1か月分のデータを取得する
        studyrecord = StudyRecord.objects.filter(user=request.user, studied_at__range=(m_start, m_end)).order_by('studied_at').select_related()

        data = {
            'labels': [i + 1 for i in range((m_end - m_start).days + 1)],
            'datasets': barchart_datasets(studyrecord, m_start, m_end)
        }

        return JsonResponse(data)


class GetBarChartDataYear(LoginRequiredMixin, generic.View):
    def get(self, request, *args, **kwargs):
        now = dt.datetime.now().astimezone()
        y_start, y_end = year_start_end(now)

        # 1年分のデータを取得する
        queryset = StudyRecord.objects.filter(user=request.user, studied_at__range=(y_start, y_end)).order_by('studied_at').select_related()

        data = {
            'labels': ('1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'),
            'datasets': barchart_datasets_year(queryset, y_start, y_end)
        }

        return JsonResponse(data)


class SubjectView(LoginRequiredMixin, generic.ListView):
    template_name = 'subject.html'

    def get_queryset(self):
        queryset = Subject.objects.filter(user=self.request.user, is_available=True).order_by('created_at')
        return queryset


class SubjectCreateView(LoginRequiredMixin, generic.CreateView):
    template_name = 'subject_create.html'
    form_class = SubjectCreateForm

    def get(self, request, **kwargs):
        request.session['via'] = request.META['HTTP_REFERER']
        return super().get(request, **kwargs)

    def get_success_url(self):
        success_url = self.request.session['via']
        del self.request.session['via']
        return success_url

    def form_valid(self, form):
        subject = form.save(commit=False)
        subject.user = self.request.user
        subject.save()

        messages.success(self.request, '教科を作成しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, '教科の作成に失敗しました。')
        return super().form_invalid(form)


class SubjectUpdateView(LoginRequiredMixin, generic.UpdateView):
    template_name = 'subject_update.html'
    model = Subject
    fields = ('name', 'color')
    success_url = reverse_lazy('study:subject')

    def form_valid(self, form):
        messages.success(self.request, '教科を更新しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, '教科の更新に失敗しました。')
        return super().form_invalid(form)



class SubjectDeleteView(LoginRequiredMixin, generic.View):
    def post(self, request, *args, **kwargs):
        subject = Subject.objects.get(pk=kwargs['pk'])
        # StudyRecordのsubjectフィールドはSubjectモデルを外部キーに設定しているため、
        # Subjectのレコードを削除するのではなく、使用不可（is_availavle = False）に設定する
        subject.is_available = False
        subject.save()
        messages.success(request, '教科を削除しました。')
        return HttpResponseRedirect(reverse_lazy('study:subject'))


class AccountSearchView(LoginRequiredMixin, generic.ListView):
    template_name = 'accout_search.html'

    def get_queryset(self):
        queryset = CustomUser.objects.none()
        query = self.request.GET.get('query')
        if query:
            queryset = CustomUser.objects.filter(Q(username__icontains=query) | Q(introduce__icontains=query)).exclude(username=self.request.user.username)
        return queryset


class AccountDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = 'account_detail.html'
    model = CustomUser
    slug_field = 'username'
    slug_url_kwarg = 'username'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['account'] = CustomUser.objects.get(pk=self.kwargs['pk'])
        context['following'] = Connection.objects.filter(follower=self.kwargs['pk']).count()
        context['follower'] = Connection.objects.filter(following=self.kwargs['pk']).count()

        if self.kwargs['pk'] is not self.request.user:
            result = Connection.objects.filter(follower=self.request.user).filter(following=self.kwargs['pk'])
            context['connected'] = True if result else False

        return context


class AccountUpdateView(LoginRequiredMixin, generic.UpdateView):
    template_name = 'account_update.html'
    model = CustomUser
    fields = ('username', 'introduce', 'icon')

    def get_success_url(self):
        return reverse_lazy('study:account_detail', kwargs={'pk': self.request.user.pk })

    def form_valid(self, form):
        account = form.save(commit=False)
        self.request.user.username = account.username

        messages.success(self.request, 'プロフィールを更新しました。')
        return super().form_valid(form)

    def form_invalid(self, form):

study_record/study/templates/account_detail.html
{% extends 'base.html' %}

{% load static %}

{% load widget_tweaks %}

{% block title %}{{ account.username }} | StudyRecord{% endblock %}

{% block active_account_detail %}
{% if account.username == user.username %}active{% endif %}
{% endblock %}

{% block contents %}
<main class="container-md" style="max-width: 720px; margin-bottom: 10rem;">
    <div class="card card-body d-flex justify-content-center text-center shadow-sm mb-3 py-4">
        {% if account.icon %}
            <img src="/media/{{ account.icon }}" alt="{{ account.username }}" width="64" height="64" class="rounded-circle mx-auto mb-2">
        {% else %}
            <img src="{% static 'images/default_icon.png' %}" alt="{{ user.username }}" width="64" height="64" class="rounded-circle mx-auto mb-2">
        {% endif %}
        <h6 class="mb-3">{{ account.username }}</h6>

        <!-- 自己紹介 -->
        {% if account.introduce %}
            <p class="col-9 mx-auto text-start mb-3">{{ account.introduce }}</p>
        {% endif %}

        {% if account.pk == user.pk %}
            <a class="btn btn-outline-primary rounded-pill col-8 mx-auto mb-3" href="{% url 'study:account_update' account.pk %}" role="button">プロフィール編集</a>
        {% elif connected %}
            <a class="btn btn-secondary rounded-pill col-8 mx-auto mb-3" href="{% url 'study:unfollow' account.pk %}" role="button">フォロー解除</a>
        {% else %}
            <a class="btn btn-primary rounded-pill col-8 mx-auto mb-3" href="{% url 'study:follow' account.pk %}" role="button">フォロー</a>
        {% endif %}
        <div class="hstack gap-3 mx-auto">
            <a class="fw-light text-decoration-none" href="{% url 'study:account_following' account.pk %}" style="font-size: 0.9rem;">フォロー : {{ following }}</a>
            <a class="fw-light text-decoration-none" href="{% url 'study:account_followers' account.pk %}" style="font-size: 0.9rem;">フォロワー : {{ follower }}</a>
        </div>
    </div>
</main>
{% endblock %}

study_record/study/templates/base.html
{% load static %}

<!DOCTYPE html>
<html class="bg-light" lang="ja">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">
    <!-- Material Symbols -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0">
    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/2a2e490519.js" crossorigin="anonymous"></script>
    <!-- Tempus Dominus -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempus-dominus/6.2.4/css/tempus-dominus.min.css" crossorigin="anonymous">
    <!-- My style -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body class="bg-light">
    <header class="navbar navbar-expand-sm navbar-light bg-white shadow-sm fixed-top">
        <div class="container-fluid px-5">
            <a class="navbar-brand fw-bold" href="{% url 'study:home' %}">StudyRecord</a>
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link {% block active_home %}{% endblock %}" href="{% url 'study:home' %}"><i class="bi bi-house-door mx-1"></i>ホーム</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% block active_report %}{% endblock %}" href="{% url 'study:report' %}"><i class="bi bi-bar-chart-line mx-1"></i>レポート</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% block active_qa %}{% endblock %}" href="{% url 'qa:qa' %}"><i class="bi bi-chat-text mx-1"></i>Q&ampA</a>
                        </li>
                        <li class="nav-item d-sm-none">
                            <a class="nav-link {% block active_subject %}{% endblock %}" href="{% url 'study:subject' %}"><i class="bi bi-book mx-1"></i>教科一覧</a>
                        </li>
                        <li class="nav-item d-sm-none">
                            <a class="nav-link {% block active_account_search %}{% endblock %}" href="{% url 'study:account_search' %}">アカウントを探す</a>
                        </li>
                        <li class="nav-item d-sm-none">
                            <a class="nav-link {% block active_account_detail %}{% endblock %}" href="{% url 'study:account_detail' user.pk %}">プロフィール</a>
                        </li>
                        <li class="nav-item d-sm-none">
                            <a class="nav-link" href="{% url 'account_logout' %}">ログアウト</a>
                        </li>
                    {% endif %}
                </ul>
                <ul class="navbar-nav ms-auto">
                    {% if user.is_authenticated %}
                        <li class="nav-item d-none d-sm-block">
                            <div class="dropdown">
                                <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                    {% if user.icon %}
                                        <img src="/media/{{ user.icon }}" alt="{{ user.username }}" width="32" height="32" class="rounded-circle">
                                    {% else %}
                                        <img src="{% static 'images/default_icon.png' %}" alt="{{ user.username }}" width="32" height="32" class="rounded-circle">
                                    {% endif %}
                                </a>
                                <ul class="dropdown-menu dropdown-menu-end">
                                    <li><a class="dropdown-item" href="{% url 'study:account_detail' user.pk %}">プロフィール</a></li>
                                    <li><a class="dropdown-item" href="{% url 'study:subject' %}">教科一覧</a></li>
                                    <li><a class="dropdown-item" href="{% url 'study:account_search' %}">アカウントを探す</a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item" href="{% url 'account_logout' %}">ログアウト</a></li>
                                </ul>
                            </div>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link {% block active_login %}{% endblock %}" href="{% url 'account_login' %}">ログイン</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% block active_signup %}{% endblock %}" href="{% url 'account_signup' %}">サインアップ</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </header>

    <!-- メッセージフレームワーク -->
    <div class="container-md">
        {% for message in messages %}
            <div class="{{ message.tags }} alert-dismissible fade show" role="alert">
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="閉じる"></button>
                <span>{{ message }}<span>
            </div>
        {% endfor %}
    </div>

    {% block contents %}{% endblock %}

    <!-- Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>

    {% block script %}{% endblock %}
</body>

</html>

study_record/study/templates/home.html
{% extends 'base.html' %}

{% load static %}

{% load widget_tweaks %}

{% block title %}StudyRecord{% endblock %}

{% block active_home %}active{% endblock %}

{% block contents %}
<main class="container-lg" style="margin-bottom: 10rem;">
    <div class="row">
        <div class="col-lg-8 mb-4">
            <div class="card shadow-sm">
                <h6 class="card-header py-3">自分の記録</h6>
                <div class="card-body p-0">
                    {% if studyrecord_list %}
                        <div class="table-responsive-sm">
                            <table class="table table-hover" id="myRecordTable" style="">
                                <thead>
                                    <tr>
                                        <th class="px-4    fw-light text-muted" scope="col" style="font-size: 11pt;">教科</th>
                                        <th class="px-sm-4 fw-light text-muted" scope="col" style="font-size: 11pt;">学習時間</th>
                                        <th class="px-sm-4 fw-light text-muted" scope="col" style="font-size: 11pt;">公開設定</th>
                                        <th class="px-sm-4 fw-light text-muted" scope="col" style="font-size: 11pt;">日時</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for studyrecord in studyrecord_list %}
                                        <tr class="position-relative" data-href="{% url 'study:studyrecord_update' studyrecord.pk %}" role="button">
                                            <td class="p-0">
                                                <div class="px-4 py-2 py-sm-3" style="border-left: 10px solid {{ studyrecord.subject.color }};">{{ studyrecord.subject }}</div>
                                            </td>
                                            <td class="px-sm-4 py-sm-3">{{ studyrecord.minutes }}</td>
                                            <td class="px-sm-4 py-sm-3">{% if studyrecord.publication == 'follow' %}公開{% else %}非公開{% endif %}</td>
                                            <td class="px-sm-4 py-sm-3">{{ studyrecord.studied_at|date:'n/j G:i' }}</td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    {% else %}
                        <div class="col-12 py-5 text-center">記録がありません</div>
                    {% endif %}
                </div>

                <!-- ページネーション -->
                {% if is_paginated %}
                    <div class="card-footer border-top-0 d-flex">
                        <ul class="pagination pagination-sm justify-content-center ms-auto mb-0">
                            <!-- 前ページへのリンク -->
                            {% if page_obj.has_previous %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if tab %}&tab={{ tab }}{% endif %}">&laquo;</a>
                                </li>
                            {% else %}
                                <li class="page-item disabled"><a class="page-link">&laquo;</a></li>
                            {% endif %}
                            <!-- ページ数表示 -->
                            {% for page_num in page_obj.paginator.page_range %}
                                {% if page_obj.number == page_num %}
                                    <li class="page-item active"><a class="page-link" href="#">{{ page_num }}</a></li>
                                {% else %}
                                    <li class="page-item"><a class="page-link" href="?page={{ page_num }}{% if tab %}&tab={{ tab }}{% endif %}">{{ page_num }}</a></li>
                                {% endif %}
                            {% endfor %}
                            <!-- 次ページへのリンク -->
                            {% if page_obj.has_next %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ page_obj.next_page_number }}{% if tab %}&tab={{ tab }}{% endif %}">&raquo;</a>
                                </li>
                            {% else %}
                                <li class="page-item disabled"><a class="page-link">&raquo;</a></li>
                            {% endif %}
                        </ul>
                    </div>
                {% endif %}
            </div>
        </div>

        <div class="col-lg-4">
            <div class="vstack gap-4" style="position: sticky; top: 5rem;">
                <a class="btn btn-primary d-none d-lg-block col-12" href="{% url 'study:studyrecord_create' %}" role="button">記録の作成</a>

                <div class="card shadow-sm">
                    <h6 class="card-header py-3">フォローユーザーの記録</h6>
                    <ul class="list-group list-group-flush">
                        {% if following_records %}
                            {% for following_record in following_records %}
                                <li class="list-group-item px-lg-4">
                                    <div class="hstack mb-2">
                                        <a class="text-decoration-none" href="{% url 'study:account_detail' following_record.user.pk %}">
                                            {% if following_record.user.icon %}
                                                <img src="/media/{{ following_record.user.icon }}" alt="{{ following_record.user.username }}" width="26" height="26" class="rounded-circle">
                                            {% else %}
                                                <img src="{% static 'images/default_icon.png' %}" alt="{{ user.username }}" width="26" height="26" class="rounded-circle">
                                            {% endif %}
                                            <small>{{ following_record.user.username }}</small>
                                        </a>
                                    </div>
                                    <div class="card card-body hstack gap-3">
                                        <span>{{ following_record.subject }}</span>
                                        <span>{{ following_record.minutes }}</span>
                                        <small class="text-muted ms-auto">{{ following_record.studied_at|date:'n/j G:i' }}</small>
                                    </div>
                                </li>
                            {% endfor %}
                        {% else %}
                            <li class="list-group-item py-4 text-center">記録がありません</li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <a class="btn btn-primary rounded-circle d-lg-none position-fixed bottom-0 end-0 m-3 d-flex justify-content-center align-items-center" style=" width: 56px; height: 56px;" href="{% url 'study:studyrecord_create' %}" role="button"><div class="material-symbols-outlined">add</div></a>
</main>
{% endblock %}

{% block script %}
<script>
    document.querySelectorAll('#myRecordTable > tbody > tr').forEach((element) => {
        element.onclick = event => {
            window.location.href = event.currentTarget.dataset.href;
        }
    });
</script>
{% endblock %}